### ISSUE TITLE
Results for baselines

### ISSUE THREAD

**Issue by kgarg8** [BorealisAI/keyphrase-generation#1]
Hi,

Do you have have baseline model files e.g. ```catSeq```, ```catSeqD```, ```catSeqCorr```, ```catSeqTG```, ```catSeqTG2RF1```? You must be using them for diversity evaluation.

**Comment by HareeshBahuleyan** [comment]
Hi @kgarg8, for training the baselines, we use the open-source code provided by Chan et al. (2019): https://github.com/kenchan0226/keyphrase-generation-rl

Once we have the output keyphrases on the testset, we run it through our evaluation scripts to obtain the quality and diversity metrics.

**Comment by kgarg8** [comment]
Makes sense, thanks Hareesh for the reply.
